name: Build Production Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'Dockerfile.prod'

jobs:
  build-prod-image:
    name: Build and Push Production Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push prod image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.prod
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/sahilas/rails-base:prod
            ghcr.io/sahilas/rails-base:prod-${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test prod image
        run: |
          echo "🧪 Testing production image..."
          docker run --rm ghcr.io/sahilas/rails-base:prod ruby --version
          docker run --rm ghcr.io/sahilas/rails-base:prod bundle --version  
          docker run --rm ghcr.io/sahilas/rails-base:prod node --version
          echo "✅ Production image tests passed!"